### ISSUE TITLE
Full market data support

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#7]

**Comment by robevansuk** [comment]
Think this is added

**Comment by duanemay** [comment]
I agree. it is there and my app has been using the Top 50 level (but in building my app I tested other levels).

A suggestion would be to pass an enum instead of a string for the level. 
private static final String BEST_ORDERS = "1";
private static final String TOP_50_ORDERS = "2";
private static final String FULL_ORDERS = "3";

MarketData marketDataOrderBook = marketDataService.getMarketDataOrderBook(product, TOP_50_ORDERS);

**Comment by robevansuk** [comment]
+ 1 will try and update with sensible constants in the next version. Implementing the level 3 orderbook is taking considerable time on my part due to other commitments but should be available in the next 4-8 weeks with any luck.

**Comment by irufus** [comment]
Closing it for now. Noted that upvotes will likely come in the future.
